M48
; DRILL file {KiCad (6.0.0-0)} date Monday, March 06, 2023 at 10:31:17 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-06T22:31:17-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
%
G90
G05
T1
X2.2874Y-4.8622
X2.3091Y-2.7539
X8.7047Y-4.8602
X8.7756Y-2.7323
T0
M30
